### ISSUE TITLE
Uint8Array returns double for indexer.

### ISSUE THREAD

**Issue by hardhub** [Retyped/Retyped#58] opened 2018-05-12 14:32 UTC
Indexer returns double, we have to cast to byte, but it is overkill.  
We do not need "Bridge.Int.clipu8" there.  

https://deck.net/7521e17e0f5ef77632c8298d1a8ce8c1

```
main: function Main () {
            var array = new Uint8Array(10);

            array[1] = 255;

            var b = Bridge.Int.clipu8(array[1]);

            System.Console.WriteLine(array);
        }
```

**Comment by AndreyChechel** [comment] 2018-05-14 14:02
Hi @hardhub,

Thanks for reporting this issue!

The issue is caused by the source [declaration file](https://github.com/Microsoft/TypeScript/blob/d990f294f8703b4d3346b34b7d984cd9f91c2868/lib/lib.es5.d.ts#L2098) which declares the returning type of the indexer as `number`. Retyped uses `double` when translating TypeScript `number` type to C#.

In the sample you provided it's obvious that the type could be narrowed down to the specific primitive type. We're investigating possible ways of emitting more accurate types by using Web IDL specification. For now you can use unsafe casting to avoid emitting `Bridge.Int.clipu8` call:
```cs
byte b = array[1].As<byte>();
```

**Comment by hardhub** [comment] 2018-05-14 19:42
Nice trick with As.

Unfortunately I will switch back to Bridge.Html5 and Bridge.Jquery2.  
I explained it here: https://github.com/bridgedotnet/Bridge/issues/3493

And I think I will have to create own fork of it.

**Comment by AndreyChechel** [comment] 2018-05-30 18:56
I'm glad to share that now Retyped compiler uses Web IDL specifications providing type information missing in TypeScript declaration files. 

Many primitive numeric types have been clarified in packages **Retyped.es5** and **Retyped.dom**. That brings much value to many declarations, especially to the typed arrays.

Closing the issue, the packages are scheduled to be updated within **release 1.6**.

**Closed by AndreyChechel** 2018-05-30 18:56 UTC
Labels: feature, premium
